version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_local
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: boleto_ai_api_db
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    restart: unless-stopped

  boleto-api:
    build: .
    container_name: boleto_api
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
